spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/my_soup_db2
    username: postgres
    password: Chhinghor7944!
    driverClassName: org.postgresql.Driver